import { env } from "cloudflare:test";
import { describe, expect, it } from "vitest";
import { ProcessPaper } from "../src/application/ingestion/process-paper";
import { createDb } from "../src/db/client";
import type {
  Embedder,
  ExtractedDoc,
  FolderAssigner,
  Tagger,
  TextExtractor,
} from "../src/domain/ingestion/extraction";
import type { VectorIndex, VectorRecord } from "../src/domain/search/vector-index";
import { r2Keys } from "../src/domain/storage/keys";
import {
  DrizzleChunkRepository,
  DrizzleFolderRepository,
  DrizzlePaperRepository,
  DrizzleTagRepository,
} from "../src/infrastructure/repositories/library";
import { R2ObjectStorage } from "../src/infrastructure/storage/r2-object-storage";
import { seedUser } from "./helpers";

const DOC: ExtractedDoc = {
  lang: "en",
  sections: [
    { heading: "Intro", paragraphs: ["p one", "p two"] },
    { heading: "Method", paragraphs: ["m one"] },
  ],
};

class StubExtractor implements TextExtractor {
  extract(): Promise<ExtractedDoc> {
    return Promise.resolve(DOC);
  }
}
class StubTagger implements Tagger {
  suggest(): Promise<{ name: string; kind: "field" | "topic" | "method" }[]> {
    return Promise.resolve([
      { name: "nlp", kind: "topic" },
      { name: "transformers", kind: "method" },
    ]);
  }
}
class StubFolderAssigner implements FolderAssigner {
  calls = 0;
  assign(): Promise<{ name: string }> {
    this.calls++;
    return Promise.resolve({ name: "NLP" });
  }
}
class StubEmbedder implements Embedder {
  embed(texts: string[]): Promise<number[][]> {
    return Promise.resolve(texts.map(() => [0.1, 0.2, 0.3]));
  }
}
class RecordingIndex implements VectorIndex {
  readonly upserts: VectorRecord[][] = [];
  readonly deletes: string[][] = [];
  upsert(records: VectorRecord[]): Promise<void> {
    this.upserts.push(records);
    return Promise.resolve();
  }
  query(): Promise<never[]> {
    return Promise.resolve([]);
  }
  deleteVectors(ids: string[]): Promise<void> {
    this.deletes.push(ids);
    return Promise.resolve();
  }
}

const deps = () => {
  const db = createDb(env.DB);
  return {
    papers: new DrizzlePaperRepository(db),
    folders: new DrizzleFolderRepository(db),
    tags: new DrizzleTagRepository(db),
    chunks: new DrizzleChunkRepository(db),
    storage: new R2ObjectStorage(env.BUCKET),
    extractor: new StubExtractor(),
    tagger: new StubTagger(),
    folderAssigner: new StubFolderAssigner(),
    embedder: new StubEmbedder(),
    vectorIndex: new RecordingIndex(),
  };
};

describe("ProcessPaper pipeline", () => {
  it("extracts, persists text, tags, assigns a folder, chunks, embeds, indexes", async () => {
    const d = deps();
    const userId = await seedUser();
    const paper = await d.papers.create({
      id: crypto.randomUUID(),
      userId,
      title: "Attn",
      abstract: "abs",
    });

    await new ProcessPaper(d).execute({ userId, paperId: paper.id });

    const updated = await d.papers.findById(userId, paper.id);
    expect(updated?.textR2Key).toBe(r2Keys.text(userId, paper.id));
    expect(await d.storage.getText(r2Keys.text(userId, paper.id))).toContain("Intro");

    expect(await d.tags.listForPaper(userId, paper.id)).toHaveLength(2);

    expect(d.folderAssigner.calls).toBe(1);
    expect((await d.folders.list(userId)).map((f) => f.name)).toContain("NLP");
    expect(updated?.primaryFolderId).toBeTruthy();

    const chunks = await d.chunks.listByPaper(userId, paper.id);
    expect(chunks).toHaveLength(2); // Intro (2 paras merged) + Method
    expect(d.vectorIndex.upserts).toHaveLength(1);
    expect(d.vectorIndex.upserts[0]).toHaveLength(2);
    expect(d.vectorIndex.upserts[0]?.every((v) => v.userId === userId)).toBe(true);
  });

  it("does not reassign a folder the user already set (non-destructive)", async () => {
    const d = deps();
    const userId = await seedUser();
    const manual = await d.folders.create({
      id: crypto.randomUUID(),
      userId,
      name: "Manual",
      autoGenerated: false,
    });
    const paper = await d.papers.create({
      id: crypto.randomUUID(),
      userId,
      title: "X",
      abstract: "a",
      primaryFolderId: manual.id,
    });

    await new ProcessPaper(d).execute({ userId, paperId: paper.id });

    expect(d.folderAssigner.calls).toBe(0);
    expect((await d.papers.findById(userId, paper.id))?.primaryFolderId).toBe(manual.id);
  });

  it("is idempotent on re-processing (replaces chunks/vectors, no growth)", async () => {
    const d = deps();
    const userId = await seedUser();
    const paper = await d.papers.create({
      id: crypto.randomUUID(),
      userId,
      title: "X",
      abstract: "a",
    });
    const proc = new ProcessPaper(d);

    await proc.execute({ userId, paperId: paper.id });
    await proc.execute({ userId, paperId: paper.id });

    expect(await d.chunks.listByPaper(userId, paper.id)).toHaveLength(2);
    expect(d.vectorIndex.deletes).toHaveLength(1); // second run cleared the first run's vectors
  });

  it("still produces a readable paper when tagging + embedding fail (non-fatal)", async () => {
    const db = createDb(env.DB);
    const d = {
      papers: new DrizzlePaperRepository(db),
      folders: new DrizzleFolderRepository(db),
      tags: new DrizzleTagRepository(db),
      chunks: new DrizzleChunkRepository(db),
      storage: new R2ObjectStorage(env.BUCKET),
      extractor: new StubExtractor(),
      tagger: { suggest: () => Promise.reject(new Error("LLM gateway 502")) } as Tagger,
      folderAssigner: new StubFolderAssigner(),
      embedder: { embed: () => Promise.reject(new Error("AI unavailable")) } as Embedder,
      vectorIndex: new RecordingIndex(),
    };
    const userId = await seedUser();
    const paper = await d.papers.create({
      id: crypto.randomUUID(),
      userId,
      title: "X",
      abstract: "a",
    });

    // Must not throw even though the LLM tagger and the embedder both reject.
    await new ProcessPaper(d).execute({ userId, paperId: paper.id });

    const updated = await d.papers.findById(userId, paper.id);
    expect(updated?.textR2Key).toBe(r2Keys.text(userId, paper.id)); // reflow text persisted
    expect(await d.chunks.listByPaper(userId, paper.id)).toHaveLength(2); // chunks persisted
    expect(await d.tags.listForPaper(userId, paper.id)).toHaveLength(0); // tagging skipped
    expect(d.vectorIndex.upserts).toHaveLength(0); // embedding skipped
  });

  it("falls back to a tag-derived folder when the LLM folder-assigner fails", async () => {
    const db = createDb(env.DB);
    const d = {
      papers: new DrizzlePaperRepository(db),
      folders: new DrizzleFolderRepository(db),
      tags: new DrizzleTagRepository(db),
      chunks: new DrizzleChunkRepository(db),
      storage: new R2ObjectStorage(env.BUCKET),
      extractor: new StubExtractor(),
      tagger: new StubTagger(), // [{nlp, topic}, {transformers, method}]
      folderAssigner: { assign: () => Promise.reject(new Error("gateway 429")) } as FolderAssigner,
      embedder: new StubEmbedder(),
      vectorIndex: new RecordingIndex(),
    };
    const userId = await seedUser();
    const paper = await d.papers.create({
      id: crypto.randomUUID(),
      userId,
      title: "X",
      abstract: "a",
    });

    await new ProcessPaper(d).execute({ userId, paperId: paper.id });

    const updated = await d.papers.findById(userId, paper.id);
    expect(updated?.primaryFolderId).toBeTruthy(); // never left uncategorized
    const folders = await d.folders.list(userId);
    // Fallback uses the top tag (StubTagger's first is "nlp").
    expect(folders.find((f) => f.id === updated?.primaryFolderId)?.name).toBe("nlp");
  });
});
