import { env } from "cloudflare:test";
import { describe, expect, it } from "vitest";
import { ReclassifyPaper } from "../src/application/ingestion/reclassify-paper";
import { createDb } from "../src/db/client";
import type { FolderAssigner } from "../src/domain/ingestion/extraction";
import {
  DrizzleFolderRepository,
  DrizzlePaperRepository,
  DrizzleTagRepository,
} from "../src/infrastructure/repositories/library";
import { seedUser } from "./helpers";

const deps = (folderAssigner: FolderAssigner) => {
  const db = createDb(env.DB);
  return {
    papers: new DrizzlePaperRepository(db),
    folders: new DrizzleFolderRepository(db),
    tags: new DrizzleTagRepository(db),
    folderAssigner,
  };
};

const okAssigner = (name: string): FolderAssigner => ({ assign: () => Promise.resolve({ name }) });
const failAssigner: FolderAssigner = { assign: () => Promise.reject(new Error("gateway 429")) };

describe("ReclassifyPaper (user-triggered)", () => {
  it("moves an uncategorized paper into the LLM-chosen folder", async () => {
    const d = deps(okAssigner("NLP"));
    const userId = await seedUser();
    const paper = await d.papers.create({
      id: crypto.randomUUID(),
      userId,
      title: "X",
      abstract: "a",
    });

    const res = await new ReclassifyPaper(d).execute(userId, paper.id);

    expect(res.folderName).toBe("NLP");
    expect((await d.papers.findById(userId, paper.id))?.primaryFolderId).toBe(res.folderId);
    expect((await d.folders.list(userId)).map((f) => f.name)).toContain("NLP");
  });

  it("re-homes a paper that already had a folder (unlike ingestion)", async () => {
    const d = deps(okAssigner("NLP"));
    const userId = await seedUser();
    const manual = await d.folders.create({
      id: crypto.randomUUID(),
      userId,
      name: "Old",
      autoGenerated: false,
    });
    const paper = await d.papers.create({
      id: crypto.randomUUID(),
      userId,
      title: "X",
      abstract: "a",
      primaryFolderId: manual.id,
    });

    const res = await new ReclassifyPaper(d).execute(userId, paper.id);

    expect(res.folderId).not.toBe(manual.id);
    expect((await d.papers.findById(userId, paper.id))?.primaryFolderId).toBe(res.folderId);
  });

  it("reuses an existing folder when the name matches (case-insensitive)", async () => {
    const d = deps(okAssigner("NLP"));
    const userId = await seedUser();
    const existing = await d.folders.create({ id: crypto.randomUUID(), userId, name: "nlp" });
    const paper = await d.papers.create({
      id: crypto.randomUUID(),
      userId,
      title: "X",
      abstract: "a",
    });

    const res = await new ReclassifyPaper(d).execute(userId, paper.id);

    expect(res.folderId).toBe(existing.id);
    expect(await d.folders.list(userId)).toHaveLength(1); // no duplicate
  });

  it("falls back to the top tag when the LLM assigner fails", async () => {
    const d = deps(failAssigner);
    const userId = await seedUser();
    const paper = await d.papers.create({
      id: crypto.randomUUID(),
      userId,
      title: "X",
      abstract: "a",
    });
    const tag = await d.tags.upsert({
      id: crypto.randomUUID(),
      userId,
      name: "nlp",
      kind: "topic",
    });
    await d.tags.attachToPaper(userId, paper.id, tag.id);

    const res = await new ReclassifyPaper(d).execute(userId, paper.id);

    expect(res.folderName).toBe("nlp");
    expect((await d.papers.findById(userId, paper.id))?.primaryFolderId).toBeTruthy();
  });

  it("throws not_found for a missing or cross-tenant paper", async () => {
    const d = deps(okAssigner("NLP"));
    const u1 = await seedUser();
    const u2 = await seedUser();
    const paper = await d.papers.create({
      id: crypto.randomUUID(),
      userId: u1,
      title: "X",
      abstract: "a",
    });

    await expect(new ReclassifyPaper(d).execute(u2, paper.id)).rejects.toThrow();
  });
});
