import { env } from "cloudflare:test";
import { describe, expect, it } from "vitest";
import { createDb } from "../src/db/client";
import {
  DrizzleChunkRepository,
  DrizzleFolderRepository,
  DrizzlePaperRepository,
  DrizzleTagRepository,
} from "../src/infrastructure/repositories/library";
import { DrizzleProfileRepository } from "../src/infrastructure/repositories/profile";
import { seedUser } from "./helpers";

describe("repositories force user_id scoping", () => {
  it("paper: dedupe lookups + cross-user isolation on read and write", async () => {
    const repo = new DrizzlePaperRepository(createDb(env.DB));
    const u1 = await seedUser();
    const u2 = await seedUser();

    const p = await repo.create({
      id: crypto.randomUUID(),
      userId: u1,
      title: "Attention Is All You Need",
      authors: ["Vaswani et al."],
      arxivId: "1706.03762",
    });
    expect(p.status).toBe("unread");
    expect(p.authors).toEqual(["Vaswani et al."]);

    // Other tenant cannot read by id or by dedupe keys.
    expect(await repo.findById(u2, p.id)).toBeNull();
    expect(await repo.findByArxivId(u2, "1706.03762")).toBeNull();
    expect(await repo.list(u2)).toHaveLength(0);

    // Owner can.
    expect((await repo.findById(u1, p.id))?.title).toContain("Attention");
    expect(await repo.findByArxivId(u1, "1706.03762")).not.toBeNull();

    // Other tenant cannot mutate the owner's row.
    await repo.setStatus(u2, p.id, "read");
    expect((await repo.findById(u1, p.id))?.status).toBe("unread");
    await repo.setStatus(u1, p.id, "reading");
    expect((await repo.findById(u1, p.id))?.status).toBe("reading");
  });

  it("folder: home folder assignment is scoped", async () => {
    const db = createDb(env.DB);
    const folders = new DrizzleFolderRepository(db);
    const papers = new DrizzlePaperRepository(db);
    const u1 = await seedUser();

    const f = await folders.create({ id: crypto.randomUUID(), userId: u1, name: "Transformers" });
    expect(f.autoGenerated).toBe(true);
    const p = await papers.create({ id: crypto.randomUUID(), userId: u1, title: "X" });
    await papers.setPrimaryFolder(u1, p.id, f.id);
    expect((await papers.findById(u1, p.id))?.primaryFolderId).toBe(f.id);
    expect(await folders.listChildren(u1, null)).toHaveLength(1);
  });

  it("tag: upsert is idempotent and attach is tenant-checked", async () => {
    const db = createDb(env.DB);
    const tags = new DrizzleTagRepository(db);
    const papers = new DrizzlePaperRepository(db);
    const u1 = await seedUser();
    const u2 = await seedUser();

    const t1 = await tags.upsert({
      id: crypto.randomUUID(),
      userId: u1,
      name: "nlp",
      kind: "topic",
    });
    const t1again = await tags.upsert({
      id: crypto.randomUUID(),
      userId: u1,
      name: "nlp",
      kind: "topic",
    });
    expect(t1again.id).toBe(t1.id);

    const p = await papers.create({ id: crypto.randomUUID(), userId: u1, title: "X" });
    await tags.attachToPaper(u1, p.id, t1.id);
    expect(await tags.listForPaper(u1, p.id)).toHaveLength(1);

    // Cross-tenant attach is rejected.
    await expect(tags.attachToPaper(u2, p.id, t1.id)).rejects.toThrow();
  });

  it("chunk: bulk create + scoped list/delete", async () => {
    const db = createDb(env.DB);
    const papers = new DrizzlePaperRepository(db);
    const chunks = new DrizzleChunkRepository(db);
    const u1 = await seedUser();
    const u2 = await seedUser();
    const p = await papers.create({ id: crypto.randomUUID(), userId: u1, title: "X" });

    await chunks.bulkCreate([
      { id: crypto.randomUUID(), userId: u1, paperId: p.id, idx: 0, charLen: 100 },
      { id: crypto.randomUUID(), userId: u1, paperId: p.id, idx: 1, charLen: 120 },
    ]);
    expect(await chunks.listByPaper(u1, p.id)).toHaveLength(2);
    expect(await chunks.listByPaper(u2, p.id)).toHaveLength(0);
    await chunks.deleteByPaper(u1, p.id);
    expect(await chunks.listByPaper(u1, p.id)).toHaveLength(0);
  });

  it("profile: upsert merges fields and preserves prior values", async () => {
    const profiles = new DrizzleProfileRepository(createDb(env.DB));
    const u = await seedUser();

    const a = await profiles.upsert(u, {
      interests: ["nlp", "rl"],
      domains: ["NLP"],
      organizations: ["OpenAI"],
      avoid: ["blockchain"],
      goal: "Understand LLM training",
      outputLang: "en",
    });
    expect(a.interests).toEqual(["nlp", "rl"]);
    expect(a.domains).toEqual(["NLP"]);
    expect(a.organizations).toEqual(["OpenAI"]);
    expect(a.avoid).toEqual(["blockchain"]);
    expect(a.goal).toBe("Understand LLM training");
    expect(a.outputLang).toBe("en");

    // A partial patch preserves untouched columns (including the new tag arrays).
    const b = await profiles.upsert(u, { level: "intermediate" });
    expect(b.interests).toEqual(["nlp", "rl"]);
    expect(b.domains).toEqual(["NLP"]);
    expect(b.organizations).toEqual(["OpenAI"]);
    expect(b.outputLang).toBe("en");
    expect(b.level).toBe("intermediate");

    // A brand-new profile defaults the tag arrays to [] and goal to null.
    const u2 = await seedUser();
    const fresh = await profiles.upsert(u2, {});
    expect(fresh.domains).toEqual([]);
    expect(fresh.organizations).toEqual([]);
    expect(fresh.avoid).toEqual([]);
    expect(fresh.goal).toBeNull();
  });
});
