import { chunkDocument } from "../../domain/ingestion/chunker";
import type {
  Embedder,
  FolderAssigner,
  Tagger,
  TextExtractor,
} from "../../domain/ingestion/extraction";
import type { ProcessJob } from "../../domain/ingestion/ports";
import type {
  ChunkRepository,
  FolderRepository,
  PaperRepository,
  TagRepository,
} from "../../domain/library/types";
import type { VectorIndex } from "../../domain/search/vector-index";
import { r2Keys } from "../../domain/storage/keys";
import type { ObjectStorage } from "../../domain/storage/object-storage";
import { newId } from "../../shared/id";

export interface ProcessPaperDeps {
  papers: PaperRepository;
  folders: FolderRepository;
  tags: TagRepository;
  chunks: ChunkRepository;
  storage: ObjectStorage;
  extractor: TextExtractor;
  tagger: Tagger;
  folderAssigner: FolderAssigner;
  embedder: Embedder;
  vectorIndex: VectorIndex;
}

/**
 * Async pipeline (queue consumer): extract structured text → tag → assign home
 * folder → chunk → embed → index. Automation is non-destructive: tags are
 * additive and the home folder is only auto-assigned when the user hasn't set
 * one. Re-processing is idempotent (old chunks/vectors are replaced).
 */
export class ProcessPaper {
  constructor(private readonly deps: ProcessPaperDeps) {}

  async execute(job: ProcessJob): Promise<void> {
    const { userId, paperId } = job;
    const d = this.deps;

    const paper = await d.papers.findById(userId, paperId);
    if (!paper) return;

    // 1. Extract structured text from the best source, persist to R2.
    const pdf = paper.pdfR2Key ? ((await d.storage.get(paper.pdfR2Key))?.body ?? null) : null;
    const doc = await d.extractor.extract(paper, pdf);
    const textKey = r2Keys.text(userId, paperId);
    await d.storage.put(textKey, JSON.stringify(doc), "application/json");
    await d.papers.update(userId, paperId, {
      textR2Key: textKey,
      langDetected: doc.lang ?? paper.langDetected,
    });

    const sample = doc.sections
      .flatMap((s) => s.paragraphs)
      .slice(0, 6)
      .join("\n")
      .slice(0, 2000);

    // 2. Auto-tag (additive; never removes manual tags).
    const suggestions = await d.tagger.suggest({
      title: paper.title,
      abstract: paper.abstract,
      sample,
    });
    for (const s of suggestions) {
      const tag = await d.tags.upsert({ id: newId(), userId, name: s.name, kind: s.kind });
      await d.tags.attachToPaper(userId, paperId, tag.id);
    }

    // 3. Assign a home folder only if the user hasn't placed it (respects manual moves).
    if (!paper.primaryFolderId) {
      const existing = await d.folders.list(userId);
      const { name } = await d.folderAssigner.assign({
        existingFolders: existing.map((f) => f.name),
        title: paper.title,
        abstract: paper.abstract,
        tags: suggestions.map((s) => s.name),
      });
      const match = existing.find((f) => f.name.toLowerCase() === name.toLowerCase());
      const folder =
        match ?? (await d.folders.create({ id: newId(), userId, name, autoGenerated: true }));
      await d.papers.setPrimaryFolder(userId, paperId, folder.id);
    }

    // 4. Chunk (idempotent: drop prior chunks/vectors first).
    const textChunks = chunkDocument(doc);
    const previous = await d.chunks.listByPaper(userId, paperId);
    if (previous.length > 0) {
      await d.vectorIndex.deleteVectors(previous.map((c) => c.id));
      await d.chunks.deleteByPaper(userId, paperId);
    }
    const records = textChunks.map((tc) => {
      const id = newId();
      return {
        id,
        userId,
        paperId,
        idx: tc.idx,
        section: tc.section,
        vectorId: id,
        text: tc.text,
        charLen: tc.charLen,
      };
    });
    await d.chunks.bulkCreate(records);

    // 5. Embed + index (Vectorize). Vector id = chunk id.
    if (textChunks.length > 0) {
      const embeddings = await d.embedder.embed(textChunks.map((tc) => tc.text));
      await d.vectorIndex.upsert(
        records.map((r, i) => ({
          id: r.id,
          values: embeddings[i] ?? [],
          userId,
          paperId,
          chunkIdx: r.idx,
          section: r.section,
        })),
      );
    }
  }
}
