import type { FolderAssigner } from "../../domain/ingestion/extraction";
import type { FolderRepository, PaperRepository, TagRepository } from "../../domain/library/types";
import { AppError } from "../../shared/errors";
import { newId } from "../../shared/id";

export interface ReclassifyPaperDeps {
  papers: PaperRepository;
  folders: FolderRepository;
  tags: TagRepository;
  folderAssigner: FolderAssigner;
}

/**
 * User-triggered "re-classify with AI": re-run the LLM home-folder assignment for
 * one paper (using its stored tags as context) and move it there. Unlike the
 * automatic foldering during ingestion, this always commits a home — on LLM
 * failure it falls back to a tag-derived folder, then a default — so an explicit
 * click is never wasted. Reuses an existing folder when the name matches.
 */
export class ReclassifyPaper {
  constructor(private readonly deps: ReclassifyPaperDeps) {}

  async execute(
    userId: string,
    paperId: string,
  ): Promise<{ folderId: string; folderName: string }> {
    const d = this.deps;
    const paper = await d.papers.findById(userId, paperId);
    if (!paper) throw new AppError("not_found", "paper not found");

    const tags = await d.tags.listForPaper(userId, paperId);
    const existing = await d.folders.list(userId);

    let name: string | null = null;
    try {
      const assigned = await d.folderAssigner.assign({
        existingFolders: existing.map((f) => f.name),
        title: paper.title,
        abstract: paper.abstract,
        tags: tags.map((t) => t.name),
      });
      name = assigned.name.trim() || null;
    } catch (err) {
      console.warn("reclassify foldering failed; using fallback", paperId, err);
    }

    const folderName =
      name ??
      tags.find((t) => t.kind === "field")?.name ??
      tags.find((t) => t.kind === "topic")?.name ??
      tags[0]?.name ??
      "その他";
    const match = existing.find((f) => f.name.toLowerCase() === folderName.toLowerCase());
    const folder =
      match ??
      (await d.folders.create({ id: newId(), userId, name: folderName, autoGenerated: true }));
    await d.papers.setPrimaryFolder(userId, paperId, folder.id);
    return { folderId: folder.id, folderName: folder.name };
  }
}
