import { sql } from "drizzle-orm";
import {
  index,
  integer,
  primaryKey,
  real,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";
import { user } from "./auth";

/**
 * App tables (design doc §6). Every table carries `user_id`; hot filter columns
 * are indexed (D1 bills scanned rows). Each paper has one "home folder" + many tags.
 */

const now = sql`(unixepoch())`;

export const profile = sqliteTable("profile", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  // Personalization signals fed to the suggestion ranker. The *_json columns are
  // arrays of free-text "server tags" (Discord-style); `goal` is free text.
  interestsJson: text("interests_json").notNull().default("[]"),
  domainsJson: text("domains_json").notNull().default("[]"),
  organizationsJson: text("organizations_json").notNull().default("[]"),
  avoidJson: text("avoid_json").notNull().default("[]"),
  goal: text("goal"),
  level: text("level"),
  readability: text("readability"),
  outputLang: text("output_lang", { enum: ["ja", "en"] })
    .notNull()
    .default("ja"),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().default(now),
});

export const folder = sqliteTable(
  "folder",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    parentId: text("parent_id"),
    name: text("name").notNull(),
    autoGenerated: integer("auto_generated", { mode: "boolean" }).notNull().default(true),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now),
  },
  (t) => [index("folder_user_parent_idx").on(t.userId, t.parentId)],
);

export const paper = sqliteTable(
  "paper",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    authorsJson: text("authors_json").notNull().default("[]"),
    year: integer("year"),
    venue: text("venue"),
    doi: text("doi"),
    arxivId: text("arxiv_id"),
    sourceUrl: text("source_url"),
    abstract: text("abstract"),
    langDetected: text("lang_detected"),
    status: text("status", { enum: ["unread", "reading", "read"] })
      .notNull()
      .default("unread"),
    readabilityHint: text("readability_hint"),
    primaryFolderId: text("primary_folder_id").references(() => folder.id, {
      onDelete: "set null",
    }),
    pdfR2Key: text("pdf_r2_key"),
    textR2Key: text("text_r2_key"),
    addedAt: integer("added_at", { mode: "timestamp" }).notNull().default(now),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().default(now),
  },
  (t) => [
    index("paper_user_added_idx").on(t.userId, t.addedAt),
    index("paper_user_status_idx").on(t.userId, t.status),
    index("paper_user_folder_idx").on(t.userId, t.primaryFolderId),
    uniqueIndex("paper_user_arxiv_uq").on(t.userId, t.arxivId),
    uniqueIndex("paper_user_doi_uq").on(t.userId, t.doi),
  ],
);

export const tag = sqliteTable(
  "tag",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    kind: text("kind", { enum: ["field", "topic", "method"] }).notNull(),
  },
  (t) => [uniqueIndex("tag_user_name_kind_uq").on(t.userId, t.name, t.kind)],
);

export const paperTag = sqliteTable(
  "paper_tag",
  {
    paperId: text("paper_id")
      .notNull()
      .references(() => paper.id, { onDelete: "cascade" }),
    tagId: text("tag_id")
      .notNull()
      .references(() => tag.id, { onDelete: "cascade" }),
  },
  (t) => [primaryKey({ columns: [t.paperId, t.tagId] }), index("paper_tag_tag_idx").on(t.tagId)],
);

export const chunk = sqliteTable(
  "chunk",
  {
    id: text("id").primaryKey(),
    // Denormalized user_id so every search/scoping query filters without a join.
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    paperId: text("paper_id")
      .notNull()
      .references(() => paper.id, { onDelete: "cascade" }),
    idx: integer("idx").notNull(),
    section: text("section"),
    page: integer("page"),
    vectorId: text("vector_id"),
    // Chunk text kept in D1 for reranking/answer grounding (and future FTS).
    text: text("text").notNull().default(""),
    charLen: integer("char_len").notNull().default(0),
  },
  (t) => [
    index("chunk_user_paper_idx").on(t.userId, t.paperId),
    uniqueIndex("chunk_paper_idx_uq").on(t.paperId, t.idx),
  ],
);

export const note = sqliteTable(
  "note",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    paperId: text("paper_id")
      .notNull()
      .references(() => paper.id, { onDelete: "cascade" }),
    kind: text("kind", { enum: ["note", "highlight"] }).notNull(),
    rangeJson: text("range_json"),
    body: text("body"),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now),
    // Set when a note is edited; null for never-edited notes.
    updatedAt: integer("updated_at", { mode: "timestamp" }),
  },
  (t) => [index("note_user_paper_idx").on(t.userId, t.paperId)],
);

export const suggestion = sqliteTable(
  "suggestion",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    externalId: text("external_id").notNull(),
    source: text("source", { enum: ["s2", "arxiv", "openalex"] }).notNull(),
    title: text("title").notNull(),
    authorsJson: text("authors_json").notNull().default("[]"),
    year: integer("year"),
    url: text("url"),
    // Canonical identifiers (when known) so import resolves via arXiv/DOI, not a
    // non-resolvable landing-page URL.
    arxivId: text("arxiv_id"),
    doi: text("doi"),
    kind: text("kind", { enum: ["classic", "recent"] }).notNull(),
    score: real("score").notNull().default(0),
    reason: text("reason"),
    status: text("status", { enum: ["suggested", "imported", "dismissed"] })
      .notNull()
      .default("suggested"),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now),
  },
  (t) => [
    index("suggestion_user_kind_idx").on(t.userId, t.kind),
    index("suggestion_user_status_idx").on(t.userId, t.status),
    uniqueIndex("suggestion_user_external_uq").on(t.userId, t.source, t.externalId),
  ],
);

// A Q&A conversation thread for a paper (Cursor-style: many per paper). Messages
// hang off a session so history survives closing the chat and the user can keep
// several threads.
export const qaSession = sqliteTable(
  "qa_session",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    paperId: text("paper_id")
      .notNull()
      .references(() => paper.id, { onDelete: "cascade" }),
    title: text("title").notNull().default("新しいチャット"),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().default(now),
  },
  (t) => [index("qa_session_user_paper_idx").on(t.userId, t.paperId)],
);

export const qaMessage = sqliteTable(
  "qa_message",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    paperId: text("paper_id")
      .notNull()
      .references(() => paper.id, { onDelete: "cascade" }),
    // Nullable for messages created before sessions existed; new messages always set it.
    sessionId: text("session_id").references(() => qaSession.id, { onDelete: "cascade" }),
    role: text("role", { enum: ["user", "assistant"] }).notNull(),
    content: text("content").notNull(),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now),
  },
  (t) => [
    index("qa_user_paper_idx").on(t.userId, t.paperId),
    index("qa_user_session_idx").on(t.userId, t.sessionId),
  ],
);

/**
 * Backs the D1 brute-force VectorIndex fallback (swappable search layer). Empty
 * in production where Vectorize is the active index; lets the fallback be real
 * and testable without external services.
 */
export const chunkVector = sqliteTable(
  "chunk_vector",
  {
    chunkId: text("chunk_id")
      .primaryKey()
      .references(() => chunk.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    paperId: text("paper_id")
      .notNull()
      .references(() => paper.id, { onDelete: "cascade" }),
    chunkIdx: integer("chunk_idx").notNull(),
    section: text("section"),
    embedding: text("embedding", { mode: "json" }).$type<number[]>().notNull(),
  },
  (t) => [index("chunk_vector_user_paper_idx").on(t.userId, t.paperId)],
);
