import { and, asc, count, desc, eq, inArray, isNull } from "drizzle-orm";
import type { Database } from "../../db/client";
import { chunk, folder, note, paper, paperTag, tag } from "../../db/schema";
import type {
  Chunk,
  ChunkRepository,
  Folder,
  FolderRepository,
  ListPapersOptions,
  NewChunk,
  NewNote,
  NewPaper,
  Note,
  NoteRepository,
  Paper,
  PaperPatch,
  PaperRepository,
  PaperStatus,
  Tag,
  TagRepository,
} from "../../domain/library/types";
import { AppError } from "../../shared/errors";

// ---------- Paper ----------

type PaperRow = typeof paper.$inferSelect;

const toPaper = (r: PaperRow): Paper => ({
  id: r.id,
  userId: r.userId,
  title: r.title,
  authors: JSON.parse(r.authorsJson) as string[],
  year: r.year,
  venue: r.venue,
  doi: r.doi,
  arxivId: r.arxivId,
  sourceUrl: r.sourceUrl,
  abstract: r.abstract,
  langDetected: r.langDetected,
  status: r.status,
  readabilityHint: r.readabilityHint,
  primaryFolderId: r.primaryFolderId,
  pdfR2Key: r.pdfR2Key,
  textR2Key: r.textR2Key,
  addedAt: r.addedAt,
  updatedAt: r.updatedAt,
});

export class DrizzlePaperRepository implements PaperRepository {
  constructor(private readonly db: Database) {}

  async create(input: NewPaper): Promise<Paper> {
    const rows = await this.db
      .insert(paper)
      .values({
        id: input.id,
        userId: input.userId,
        title: input.title,
        authorsJson: JSON.stringify(input.authors ?? []),
        year: input.year ?? null,
        venue: input.venue ?? null,
        doi: input.doi ?? null,
        arxivId: input.arxivId ?? null,
        sourceUrl: input.sourceUrl ?? null,
        abstract: input.abstract ?? null,
        langDetected: input.langDetected ?? null,
        primaryFolderId: input.primaryFolderId ?? null,
        pdfR2Key: input.pdfR2Key ?? null,
        textR2Key: input.textR2Key ?? null,
      })
      .returning();
    const row = rows[0];
    if (!row) throw new AppError("internal", "paper insert returned no row");
    return toPaper(row);
  }

  async findById(userId: string, id: string): Promise<Paper | null> {
    const rows = await this.db
      .select()
      .from(paper)
      .where(and(eq(paper.userId, userId), eq(paper.id, id)));
    return rows[0] ? toPaper(rows[0]) : null;
  }

  async findByArxivId(userId: string, arxivId: string): Promise<Paper | null> {
    const rows = await this.db
      .select()
      .from(paper)
      .where(and(eq(paper.userId, userId), eq(paper.arxivId, arxivId)));
    return rows[0] ? toPaper(rows[0]) : null;
  }

  async findByDoi(userId: string, doi: string): Promise<Paper | null> {
    const rows = await this.db
      .select()
      .from(paper)
      .where(and(eq(paper.userId, userId), eq(paper.doi, doi)));
    return rows[0] ? toPaper(rows[0]) : null;
  }

  async list(userId: string, options?: ListPapersOptions): Promise<Paper[]> {
    const conds = [eq(paper.userId, userId)];
    if (options?.status) conds.push(eq(paper.status, options.status));
    if (options?.folderId) conds.push(eq(paper.primaryFolderId, options.folderId));
    const rows = await this.db
      .select()
      .from(paper)
      .where(and(...conds))
      .orderBy(desc(paper.addedAt))
      .limit(options?.limit ?? 200)
      .offset(options?.offset ?? 0);
    return rows.map(toPaper);
  }

  async update(userId: string, id: string, patch: PaperPatch): Promise<void> {
    await this.db
      .update(paper)
      .set({ ...patch, updatedAt: new Date() })
      .where(and(eq(paper.userId, userId), eq(paper.id, id)));
  }

  async setStatus(userId: string, id: string, status: PaperStatus): Promise<void> {
    await this.db
      .update(paper)
      .set({ status, updatedAt: new Date() })
      .where(and(eq(paper.userId, userId), eq(paper.id, id)));
  }

  async setPrimaryFolder(userId: string, id: string, folderId: string | null): Promise<void> {
    await this.db
      .update(paper)
      .set({ primaryFolderId: folderId, updatedAt: new Date() })
      .where(and(eq(paper.userId, userId), eq(paper.id, id)));
  }

  async delete(userId: string, id: string): Promise<void> {
    await this.db.delete(paper).where(and(eq(paper.userId, userId), eq(paper.id, id)));
  }
}

// ---------- Folder ----------

export class DrizzleFolderRepository implements FolderRepository {
  constructor(private readonly db: Database) {}

  async create(input: {
    id: string;
    userId: string;
    name: string;
    parentId?: string | null;
    autoGenerated?: boolean;
  }): Promise<Folder> {
    const rows = await this.db
      .insert(folder)
      .values({
        id: input.id,
        userId: input.userId,
        name: input.name,
        parentId: input.parentId ?? null,
        autoGenerated: input.autoGenerated ?? true,
      })
      .returning();
    const row = rows[0];
    if (!row) throw new AppError("internal", "folder insert returned no row");
    return row;
  }

  async findById(userId: string, id: string): Promise<Folder | null> {
    const rows = await this.db
      .select()
      .from(folder)
      .where(and(eq(folder.userId, userId), eq(folder.id, id)));
    return rows[0] ?? null;
  }

  async list(userId: string): Promise<Folder[]> {
    return this.db.select().from(folder).where(eq(folder.userId, userId)).orderBy(asc(folder.name));
  }

  async listChildren(userId: string, parentId: string | null): Promise<Folder[]> {
    const cond =
      parentId === null
        ? and(eq(folder.userId, userId), isNull(folder.parentId))
        : and(eq(folder.userId, userId), eq(folder.parentId, parentId));
    return this.db.select().from(folder).where(cond).orderBy(asc(folder.name));
  }

  async rename(userId: string, id: string, name: string): Promise<void> {
    await this.db
      .update(folder)
      .set({ name })
      .where(and(eq(folder.userId, userId), eq(folder.id, id)));
  }

  async delete(userId: string, id: string): Promise<void> {
    await this.db.delete(folder).where(and(eq(folder.userId, userId), eq(folder.id, id)));
  }
}

// ---------- Tag ----------

export class DrizzleTagRepository implements TagRepository {
  constructor(private readonly db: Database) {}

  async upsert(input: {
    id: string;
    userId: string;
    name: string;
    kind: Tag["kind"];
  }): Promise<Tag> {
    await this.db
      .insert(tag)
      .values(input)
      .onConflictDoNothing({ target: [tag.userId, tag.name, tag.kind] });
    const rows = await this.db
      .select()
      .from(tag)
      .where(and(eq(tag.userId, input.userId), eq(tag.name, input.name), eq(tag.kind, input.kind)));
    const row = rows[0];
    if (!row) throw new AppError("internal", "tag upsert returned no row");
    return row;
  }

  async list(userId: string): Promise<Tag[]> {
    return this.db.select().from(tag).where(eq(tag.userId, userId)).orderBy(asc(tag.name));
  }

  async attachToPaper(userId: string, paperId: string, tagId: string): Promise<void> {
    await this.assertOwned(userId, paperId, tagId);
    await this.db.insert(paperTag).values({ paperId, tagId }).onConflictDoNothing();
  }

  async detachFromPaper(userId: string, paperId: string, tagId: string): Promise<void> {
    await this.assertOwned(userId, paperId, tagId);
    await this.db
      .delete(paperTag)
      .where(and(eq(paperTag.paperId, paperId), eq(paperTag.tagId, tagId)));
  }

  async listForPaper(userId: string, paperId: string): Promise<Tag[]> {
    const rows = await this.db
      .select({ id: tag.id, userId: tag.userId, name: tag.name, kind: tag.kind })
      .from(paperTag)
      .innerJoin(tag, eq(paperTag.tagId, tag.id))
      .where(and(eq(tag.userId, userId), eq(paperTag.paperId, paperId)))
      .orderBy(asc(tag.name));
    return rows;
  }

  private async assertOwned(userId: string, paperId: string, tagId: string): Promise<void> {
    const p = await this.db
      .select({ id: paper.id })
      .from(paper)
      .where(and(eq(paper.userId, userId), eq(paper.id, paperId)));
    const t = await this.db
      .select({ id: tag.id })
      .from(tag)
      .where(and(eq(tag.userId, userId), eq(tag.id, tagId)));
    if (!p[0] || !t[0]) {
      throw new AppError("forbidden", "paper or tag does not belong to user");
    }
  }
}

// ---------- Chunk ----------

export class DrizzleChunkRepository implements ChunkRepository {
  constructor(private readonly db: Database) {}

  async bulkCreate(chunks: NewChunk[]): Promise<void> {
    if (chunks.length === 0) return;
    await this.db.insert(chunk).values(
      chunks.map((c) => ({
        id: c.id,
        userId: c.userId,
        paperId: c.paperId,
        idx: c.idx,
        section: c.section ?? null,
        page: c.page ?? null,
        vectorId: c.vectorId ?? null,
        text: c.text ?? "",
        charLen: c.charLen ?? 0,
      })),
    );
  }

  async listByPaper(userId: string, paperId: string): Promise<Chunk[]> {
    return this.db
      .select()
      .from(chunk)
      .where(and(eq(chunk.userId, userId), eq(chunk.paperId, paperId)))
      .orderBy(asc(chunk.idx));
  }

  async findByIds(userId: string, ids: string[]): Promise<Chunk[]> {
    if (ids.length === 0) return [];
    return this.db
      .select()
      .from(chunk)
      .where(and(eq(chunk.userId, userId), inArray(chunk.id, ids)));
  }

  async deleteByPaper(userId: string, paperId: string): Promise<void> {
    await this.db.delete(chunk).where(and(eq(chunk.userId, userId), eq(chunk.paperId, paperId)));
  }

  async countByPaper(userId: string, paperId: string): Promise<number> {
    const rows = await this.db
      .select({ value: count() })
      .from(chunk)
      .where(and(eq(chunk.userId, userId), eq(chunk.paperId, paperId)));
    return rows[0]?.value ?? 0;
  }
}

// ---------- Note ----------

export class DrizzleNoteRepository implements NoteRepository {
  constructor(private readonly db: Database) {}

  async create(input: NewNote): Promise<Note> {
    const rows = await this.db
      .insert(note)
      .values({
        id: input.id,
        userId: input.userId,
        paperId: input.paperId,
        kind: input.kind,
        rangeJson: input.rangeJson ?? null,
        body: input.body ?? null,
      })
      .returning();
    const row = rows[0];
    if (!row) throw new AppError("internal", "note insert returned no row");
    return row;
  }

  async listByPaper(userId: string, paperId: string): Promise<Note[]> {
    return this.db
      .select()
      .from(note)
      .where(and(eq(note.userId, userId), eq(note.paperId, paperId)))
      .orderBy(desc(note.createdAt));
  }

  async delete(userId: string, id: string): Promise<void> {
    await this.db.delete(note).where(and(eq(note.userId, userId), eq(note.id, id)));
  }
}
